### ISSUE TITLE
Include api_error in BadRequest exception message

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/citrine-python#146]
Right now, bad API requests only include the route in the stacktrace.  If an error is encounted, a user has to go back and do somethign like:
```
try:
    dataset.process_runs.register(process_run)
except BadRequest as e:
    print(e.api_error)
```
to see the error.  We should include the api_error in the exception message so that it shows up in a stacktrace.

cc: @lkubie @asantas93

**Comment by asantas93** [comment]
This relates to https://citrine.atlassian.net/browse/PLA-2170

**Comment by anoto-moniz** [comment]
Done.
