### ISSUE TITLE
Serialization properties cannot be defined in parent classes

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/citrine-python#166]
Many of our `PolymorphicSerializable` class hierarchies have shared members.  It would be nice to bring these members (e.g. `key` [descriptors](https://github.com/CitrineInformatics/citrine-python/blob/develop/src/citrine/informatics/descriptors.py)) into the parent class to communicate that they are part of the interface and to deduplicate their definition.  However, the magik in those properties causes an error to be thrown when this is attempted, e.g.
```
E       assert <citrine.informatics.descriptors.InorganicDescriptor object at 0x7fe6b29af630> == <citrine.informatics.descriptors.InorganicDescriptor object at 0x7fe6945453c8>
```

Interesting, I get a completely different error when I try to do this in #163 : 
```
tests/ara/test_variables.py:9: in <module>
    RootInfo("root name", ["Root", "Name"], "name"),
src/citrine/ara/variables.py:71: in __init__
    self.short_name = short_name
src/citrine/_serialization/properties.py:114: in __set__
    getattr(base_class, self.serialization_path).fset(obj, value_to_set)
E   AttributeError: 'NoneType' object has no attribute 'fset'
```

**Comment by bfolie** [comment]
Resolved by #453
