### ISSUE TITLE
Add tests_require to setup.py

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/citrine-python#181]
Right now, the requirements for testing are included in `test_requirements.txt` but not in `setup.py`.  This isn't a bug, per se, but it could make it difficult for a developer that is building on top of citrine-python to include test-scoped dependencies (because pypi won't walk requirements files).

These test dependencies should be added with reasonably permissive version bounds, again so that a developer who is using citrine-python can flexibly test their own code.

**Comment by anoto-moniz** [comment]
The Python ecosystem is moving away from running everything through setup.py, so `tests_require` is no longer relevant, and is in fact deprecated.

- "Why you shouldn't invoke setup.py directly"(https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)
- "tests_require is now deprecated":  [](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies)
