### ISSUE TITLE
Limit discussion of access control to its own section.

### ISSUE THREAD

**Issue by gregor-robinson** [CitrineInformatics/citrine-python#191]
The current exposition of the [first technical page describing citrine-python](https://citrineinformatics.github.io/citrine-python/getting_started/basic_structure.html) describes access control in a place that distracts from the priority of describing how the pieces fit together. This can be minimized by linking to the access control section.

**Comment by bfolie** [comment]
Intro docs reorganized in https://github.com/CitrineInformatics/citrine-python/pull/510
