### ISSUE TITLE
Include soft-links in data object `__repr__`

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/citrine-python#43]
When using jupyter, the representation of the object shown in the output cell is its `__repr__`.  By default, that only shows object members, which excludes soft links.  This leads to the non-obvious behavior that `repr(process_run)` doesn't include ingredients and `repr(material_run)` doesn't include measurements.

We should override `__repr__` in objects that include soft-links to show linked objects.

h/t @sesevgen

**Comment by maxhutch** [comment]
Peer in `taurus` is https://github.com/CitrineInformatics/taurus/issues/15

**Comment by maxhutch** [comment]
The work around is to print the soft-linked return value, e.g. `print(process_run.ingredients)`

**Comment by bfolie** [comment]
Resolved in https://github.com/CitrineInformatics/taurus/pull/26
