### ISSUE TITLE
What publication(s) should I cite when referring to the Open Citrine Platform?

### ISSUE THREAD

**Issue by sgbaird** [CitrineInformatics/citrine-python#736]
Specifically the adaptive design capabilities

https://citrine.io/category/publications/

**Comment by bfolie** [comment]
There are several papers that might be applicable, depending on which aspect of the technology you'd like to refer to. But for the platform's general approach to active learning I'd suggest citing [this one](https://link.springer.com/article/10.1007/s40192-017-0098-z)

**Comment by kroenlein** [comment]
Question answered.
