### ISSUE TITLE
Guarantee unused ingredients appear in gemtable

### ISSUE THREAD

**Issue by ventura-rivera** [CitrineInformatics/citrine-python#754]
If an ingredient column is empty, it doesnt show up in the gemtable. There should be an option to have unused ingredients show up in the gemtable.

example data source:
| ID                   | ing 1            | ing 2           | ing 3 (this ingredient doesnt show up in gemtable) |
| ------------- | ----------- | ----------- | -------------------------------------------------- |
| type               | Amount       | Amount      | Amount                                                                         |
| formulation 1 | 70               | 30               |                                                                                        |
| formulation 2 | 50               | 50               |                                                                                       |
| formulation 3 | 25               | 75               |                                                                                       |

**Comment by kroenlein** [comment]
Closing now that it's referenced in the appropriate board.
